sudo: required

language: scala

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

scala:
  - 2.12.2

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

deploy:
  provider: script
  script: docker/deploy.sh $TRAVIS_TAG
  on:
    tags: true
